---
version: '3'

services:

  server:
    build: .
    image: index.docker.io/oaklabs/component-webcam:${VERSION-latest}
    network_mode: host
    environment:
      - PORT=9101
    privileged: true
    devices:
      - /dev
    volumes:
      - ./src:/src
